[package]
name = "unocss-classes-macros"
version = "1.0.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.66"
quote = "1.0.31"
syn = { version = "2.0.26", features = ["full"] }
unocss-classes-utils.workspace = true

[lib]
proc-macro = true
