[package]
name = "leptos-example"
version = "0.0.0"
edition = "2021"

[dependencies]
leptos = { version = "0.4.8", features = ["csr", "nightly"] }
leptos-use = { version = "0.6.2" }
unocss-classes = { version = "1.0.0" }
