[package]
name = "leptos-example"
version = "0.0.0"
edition = "2021"

[dependencies]
leptos = { version = "0.5.1", features = ["csr", "nightly"] }
leptos-use = { version = "0.7.1" }
unocss-classes = { version = "2.0.0", features = ["runtime"] }
