[package]
name = "leptos-example"
version = "0.0.0"
edition = "2021"

[dependencies]
leptos = { version = "0.5.0-beta", features = ["csr", "nightly"] }
leptos-use = { git = "https://github.com/Synphonyte/leptos-use.git", rev = "37f8bfc" }
unocss-classes = { path = "../.." }
