# TODO change repo name and the links below
[package]
name = "unocss-classes"
version = "0.0.0"
edition = "2021"
description = "Variant group transformer macro for UnoCSS / WindiCSS utility classes"
repository = "https://github.com/brofrain/unocss-variant-group-transformer-rs"
homepage = "https://github.com/brofrain/unocss-variant-group-transformer-rs"
license = "MIT"
keywords = [
  "unocss",
  "windicss",
  "atomic-css",
  "yew",
  "dioxus",
  "leptos",
  "ui",
  "gui",
  "dom",
  "wasm",
  "web",
]

[workspace]
resolver = "2"
members = ["packages/macros", "packages/utils"]
exclude = ["examples"]

[workspace.dependencies]
macros = { path = "packages/macros" }
utils = { path = "packages/utils" }

[dependencies]
macros.workspace = true
classes = "1.0.0"
