[package]
name = "unocss-variant-group-transformer"
version = "0.0.1"
edition = "2021"
description = "Variant group transformer macro for UnoCSS / WindiCSS utility classes"
repository = "https://github.com/brofrain/unocss-variant-group-transformer"
homepage = "https://github.com/brofrain/unocss-variant-group-transformer"
license = "MIT"
keywords = [
  "unocss",
  "windicss",
  "atomic-css",
  "yew",
  "dioxus",
  "leptos",
  "ui",
  "gui",
  "dom",
  "wasm",
  "web",
]

[dependencies]
once_cell = "1.18.0"
proc-macro2 = "1.0.66"
quote = "1.0.31"
regex = "1.9.1"
syn = "2.0.26"

[lib]
proc-macro = true
