[package]
name = "unocss-classes"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true
description = "HTML class builder macro with UnoCSS variant group transformer for web frameworks"
keywords = ["unocss", "css", "ui", "wasm", "web"]

[dependencies]
classes = "1.0.0"
unocss-classes-macros.workspace = true
unocss-classes-utils = { workspace = true, optional = true }

[features]
runtime = ["dep:unocss-classes-utils"]
