[package]
name = "leptos-example"
version = "0.0.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.4.0" }
dioxus-web = { version = "0.4.0" }
gloo = "0.8.1"
unocss-classes = { path = "../../packages/unocss-classes", features = [
  "runtime",
] }
web-sys = { version = "0.3.64" }
