[application]
name = "Dioxus App"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "Dioxus + UnoCSS"

[web.watcher]
reload_html = true
watch_path = ["src", "public"]

[web.resource]
style = ["reset-tailwind.css", "uno.css"]
script = []

[web.resource.dev]
script = []
