name: Review

on:
  push:
    branches:
      - main

  pull_request:
    branches: "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  quality:
    name: Source code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache setup
        uses: ./.github/actions/cache
      - name: cargo-make setup
        shell: bash
        run: cargo install cargo-make@0.36.13
      - name: Lint
        run: cargo make lint
      - name: Tests
        run: cargo make test
